name: Latest blog post workflow
on:
 schedule:
   - cron: '0 */6 * * *' 
 workflow_dispatch: 
jobs:
 update-readme-with-blog:
   name: Update this repo's README with latest blog posts
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
       with:
         token: ${{ secrets.GH_TOKEN }}
     - uses: gautamkrishnar/blog-post-workflow@master
       with:
         feed_list: "https://krypton.ninja/atom.xml"
         gh_token: ${{ secrets.GH_TOKEN }}
